### PR TITLE
Add missing dependancy to README

### LINKED ISSUE #14: Can't install with packer/vim-plug
> Upon running `PackerSync`

image
image

> Upon relaunching nvim

image

> Packer install command

```  
use {
    'AckslD/nvim-revJ.lua',
    requires = {'sgur/vim-textobj-parameter'},
}
```

I have also tried to install `sgur/vim-textobj-parameter` on its own and using vim-plug and the error persists, so I think there is something wrong with that module. I am on neovim v0.5.

### PR DESCRIPTION
**Pull request by ram02z**
Closes #14

### CODE REVIEW

**Comment by AckslD** [comment]
Thanks @ram02z, that's a good point. Do you know by any chance if packer allows to do eg:
```lua
use {
    'AckslD/nvim-revJ.lua',
    requires = {
        'sgur/vim-textobj-parameter',
        requires = {'kana/vim-textobj-user'},
    },
}
```
which might make it clear that `vim-textobl-user` is not a direct dependency.

**Comment by ram02z** [comment]
@AckslD I attempted to to use the following snippet and I get the same error as in the initial issue #14.  This is most likely related to behaviour described in https://github.com/wbthomason/packer.nvim/issues/87. The following snippet works however:
```
use {
    'AckslD/nvim-revJ.lua',
    requires = {
        'kana/vim-textobj-user',
        requires = {'sgur/vim-textobj-parameter'},
    },
}
```

Let me know if you prefer that format and I will update the PR accordiningly.

**Comment by AckslD** [comment]
Thanks for checking this @ram02z! No, then your original version is better imo, since it otherwise seems as if the dependencies are the other way around. I'll just add a note about it in the README :+1:

**Comment by AckslD** [comment]
Merged in #17 with an extra note in README

**Pull request merged**
